name: build_and_test

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - humble
      - jazzy
      - '*-devel'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - '*'
  workflow_dispatch:

# Do not run multiple jobs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        ros_distro: [jazzy, kilted, rolling]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: mujoco_ros2_control:${{ github.head_ref || github.ref_name }}
          target: mujoco_ros
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
          push: false
          load: true
      - name: Run tests
        run: |
          docker run --rm \
            mujoco_ros2_control:${{ github.head_ref || github.ref_name }} \
            bash -c "
              colcon test &&
              colcon test-result --verbose
            "

  pixi_jazzy_build_and_test:
    env:
      SCCACHE_DIR: ${{ github.workspace }}/.sccache
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache build directories and sccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.SCCACHE_DIR }}
          key: ${{ runner.os }}-build-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build
      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          manifest-path: pixi.toml
      - name: Build and test
        run: |
          pixi run setup-colcon
          pixi run build
          pixi run test
          pixi run test-result
